### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by espenbjorkeng** [espenbjorkeng/React-Tables#1]
Functionality:
- [ ] Date picker when editing date fields
- [ ] Regex for all input values
- [ ] Grouping reports by column(s)

Styling: 
- [ ] ESC for leave focus
- [ ] Edit-style only if value is different from initial value
- [ ] Overflow styling
- [ ] Delete button
